stages:
    - build
    - test
    - deploy

include:
    -   remote: 'https://gitlab.com/r2devops/hub/-/raw/template_release@0.2.1/jobs/template_release/template_release.yml'
    -   remote: 'https://${CI_SERVER_HOST}/${CI_PROJECT_PATH}/-/raw/$CI_COMMIT_BRANCH$CI_COMMIT_TAG/ruff.yml'

ruff:
    variables:
        PROJECT_PATH: "tests/ruff_project"

ruff-destructive:
    extends: ruff
    variables:
        PROJECT_PATH: "tests/ruff_destructive_project"
    script:
        - >
            ruff check > /dev/null 2>&1 || EXIT_CODE=$?;
            if [ $EXIT_CODE -eq 1 ]; then
                echo "'ruff check' found issues as it should"
            else
                echo "'ruff check' did not find issues as it should"
                exit 1
            fi
        - >
            ruff format > /dev/null 2>&1 || EXIT_CODE=$?;
            if [ $EXIT_CODE -eq 1 ]; then
                echo "'ruff format --check' found issues as it should"
            else
                echo "'ruff format --check' did not find issues as it should"
                exit 1
            fi