include:
  - component: $CI_SERVER_FQDN/swepy/cicd-templates/release-by-changelog/release-on-tag@2.0.0
  - component: $CI_SERVER_FQDN/swepy/cicd-templates/bump-my-version/bump-my-version@0.2.0
  - project: $CI_PROJECT_NAMESPACE/ruff
    ref: $CI_COMMIT_SHA
    file: templates/ruff.yml
    inputs:
      target-paths: tests/ruff_project

.many-folder-base:
  variables:
    RUFF_TARGET_PATHS: tests/ruff_project/src tests/ruff_project/tests

lint:ruff:check:many-folder:
  extends:
    - lint:ruff:check
    - .many-folder-base

lint:ruff:format:many-folder:
  extends:
    - lint:ruff:format
    - .many-folder-base
