include:
  - component: $CI_SERVER_FQDN/swepy/cicd-templates/release-by-changelog/release-on-tag@2.0.0
  - project: swepy/cicd-templates/ruff
    ref: $CI_COMMIT_REF_NAME
    file: templates/ruff.yml
    inputs:
      target_paths: tests/ruff_project

.many_folder:
  variables:
    TARGET_PATHS: tests/ruff_project/src tests/ruff_project/tests

ruff_check_many_folder:
  extends:
    - ruff_check
    - .many_folder

ruff_format_many_folder:
  extends:
    - ruff_format
    - .many_folder
