# uvx pre-commit install
# uvx pre-commit autoupdate
# uvx pre-commit run --all-files

default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    # https://pre-commit.com/hooks.html
    rev: v4.6.0
    hooks:
      - id: check-case-conflict  # blocking
      - id: check-merge-conflict  # blocking
      - id: detect-private-key  # blocking
      - id: fix-byte-order-marker  # auto-fix
      - id: trailing-whitespace  # auto-fix
  - repo: https://github.com/compilerla/conventional-pre-commit
    # https://www.conventionalcommits.org
    rev: v4.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [ commit-msg ]
        args: [ feat, fix, build, chore, ci, docs, style, refactor, perf, test ]
