name: Ruff

on: [ push, pull_request ]

permissions:
  contents: read

jobs:
  ruff_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ruff check
        uses: astral-sh/ruff-action@v1
  ruff_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ruff format
        uses: astral-sh/ruff-action@v1
        with:
          args: "format --check"
  ruff_check_many_folder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ruff check
        uses: astral-sh/ruff-action@v1
        with:
          src: "tests/ruff_project/src tests/ruff_project/tests"
  ruff_format_many_folder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ruff format
        uses: astral-sh/ruff-action@v1
        with:
          args: "format --check"
          src: "tests/ruff_project/src tests/ruff_project/tests"
